steps:

- id: 'generate-ssh-key'
  name: 'lgatica/openssh-client:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - ssh-keygen -t ed25519 -C "$_SSH_USER" -f $_SSH_KEY_PATH -P ""

- id: 'init'
  name: 'hashicorp/terraform:1.5.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    terraform init -backend-config="bucket=$_TF_STATES_BACKEND" -backend-config="prefix=$_ENVIRONMENT_NAME"
  dir: 'terraform'

- id: 'plan'
  name: 'hashicorp/terraform:1.5.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    export TF_VAR_ssh_private_key=$(cat $_SSH_KEY_PATH)
    export TF_VAR_ssh_public_key=$(cat $_SSH_KEY_PATH.pub)
    terraform plan -var-file=$_TF_WORKSPACE/environments/default_versions.tfvars -var-file=$_TF_WORKSPACE/environments/production.tfvars -out $_TF_WORKSPACE/.plan/apply.tfplan
    terraform show -no-color -json $_TF_WORKSPACE/.plan/apply.tfplan > $_TF_WORKSPACE/.plan/apply.json
  env:
  - 'TF_VAR_ssh_user=$_SSH_USER'
  - 'TF_VAR_environment_name=$_ENVIRONMENT_NAME'
  - 'TF_VAR_gcp_subnetwork_cidr=$_SUBNETWORK_CIDR'
  - 'TF_VAR_notifications_email=$_NOTIFICATIONS_EMAIL'
  dir: 'terraform'

- id: 'apply'
  name: 'hashicorp/terraform:1.5.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    terraform apply -auto-approve $_TF_WORKSPACE/.plan/apply.tfplan
  dir: 'terraform'

- id: get-ssh-secret
  name: gcr.io/cloud-builders/gcloud:latest
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    gcloud secrets versions access latest --secret=ssh_key_${_ENVIRONMENT_NAME}_${_SSH_USER} > $_SSH_KEY_PATH
    echo -e "" >> $_SSH_KEY_PATH
    gcloud secrets versions access latest --secret=firebase-credentials > $_FIREBASE_CREDENTIALS_PATH
    echo -e "" >> $_FIREBASE_CREDENTIALS_PATH

- id: 'install'
  name: 'cnieg/ansible:1.0.59-ansible-7.5.0-r0'
  entrypoint: 'ash'
  args: 
  - '-c'
  - |
    chmod 600 $_SSH_KEY_PATH
    chmod og-rw ~/.netrc
    ansible-galaxy install -r requirements.yml
    ansible-playbook -i inventory-$_ENVIRONMENT_NAME.yml --extra-vars "firebase_credentials=$_FIREBASE_CREDENTIALS_PATH" --user=$_SSH_USER --private-key=$_SSH_KEY_PATH playbook.yml
  env:
  - 'ANSIBLE_HOST_KEY_CHECKING=False'
  dir: 'ansible'

artifacts:
  objects:
    location: 'gs://les-sagas-mp3-build/$_ENVIRONMENT_NAME'
    paths: ['$_TF_WORKSPACE/.plan/apply.json', 'ansible/inventory-$_ENVIRONMENT_NAME.yml']

substitutions:
  _ENVIRONMENT_NAME: production
  _SSH_USER: provisioning
  _SSH_KEY_PATH: /workspace/ssh_key
  _TF_STATES_BACKEND: les-sagas-mp3-infrastructure
  _TF_WORKSPACE: /workspace/terraform
  _FIREBASE_CREDENTIALS_PATH: /workspace/firebase_credentials.json

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'
