steps:

- id: 'debug'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      ls -all /workspace

- id: 'terraform init'
  name: 'hashicorp/terraform:1.2.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    cd $TERRAFORM_WORKSPACE
    terraform init -backend-config="bucket=$_TF_STATES_BACKEND" -backend-config="prefix=production"

- id: 'terraform plan'
  name: 'hashicorp/terraform:1.2.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    cd $TERRAFORM_WORKSPACE
    terraform plan -var-file=$TERRAFORM_WORKSPACE/environments/production.tfvars -out $TERRAFORM_WORKSPACE/.plan/apply.tfplan
    terraform show -no-color -json $TERRAFORM_WORKSPACE/.plan/apply.tfplan > $TERRAFORM_WORKSPACE/.plan/apply.json
  env:
  - 'TF_VAR_ssh_public_key=$_TF_VAR_SSH_PUBLIC_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
  env:
  - 'TERRAFORM_WORKSPACE=/workspace/terraform'
