steps:

- id: 'debug'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      ls -all /workspace

- id: 'terraform init'
  name: 'hashicorp/terraform:1.2.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    terraform init -backend-config="bucket=$_TF_STATES_BACKEND" -backend-config="prefix=production"
  dir: 'terraform'

- id: 'terraform plan'
  name: 'hashicorp/terraform:1.2.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    terraform plan -var-file=$_TF_WORKSPACE/environments/production.tfvars -out $_TF_WORKSPACE/.plan/apply.tfplan
    terraform show -no-color -json $_TF_WORKSPACE/.plan/apply.tfplan > $_TF_WORKSPACE/.plan/apply.json
  env:
  - 'TF_VAR_ssh_public_key=$_TF_VAR_SSH_PUBLIC_KEY'
  dir: 'terraform'

options:
  logging: CLOUD_LOGGING_ONLY
  env:
  - '_TF_WORKSPACE=/workspace/terraform'
