- name: "Install PostgreSQL client"
  package:
    name: postgresql-client
    state: present

- name: "Copy backup script"
  template:
    src: backup.sh.j2
    dest: "{{ script_location }}/backup.sh"
    mode: 0755
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"

- name: "Copy restore script"
  template:
    src: restore.sh.j2
    dest: "{{ script_location }}/restore.sh"
    mode: 0755
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"

- name: "Add postgresql config"
  template:
    src: .pgpass.j2
    dest: "/home/{{ linux_user }}/.pgpass"
    mode: 0600
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
  no_log: true

- name: Install crontab
  package:
    name: cron
    state: present

- name: Enable cron on startup
  service:
    name: cron
    enabled: true

- name: Add cron entry
  cron:
    name: "lessagasmp3_backup"
    minute: "{{ cron.minute }}"
    hour: "{{ cron.hour }}"
    day: "{{ cron.day }}"
    month: "{{ cron.month }}"
    weekday: "{{ cron.weekday }}"
    job: "{{ script_location }}"
    user: "{{ linux_user }}"
