
- name: Read variables
  include_vars:
    file: vars.yml

- name: Download archives
  get_url:
    url: "{{ item.url }}"
    dest: /tmp/openjdk-{{ item.version }}.tar.gz
    checksum: "{{ item.checksum }}"
  loop: "{{ versions }}"

- name: Create install directory
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Decompress archives
  unarchive:
    remote_src: yes
    src: /tmp/openjdk-{{ item.version }}.tar.gz
    dest: "{{ install_dir }}"
  loop: "{{ versions }}"

- name: Get unarchive file names
  find:
    paths: "{{ install_dir }}"
    file_type: directory
    patterns: 'jdk-{{ item.version }}*'
  loop: "{{ versions }}"
  register: java_home

- name: Add switch version script
  template:
    src: setjava.sh.j2
    dest: ~/.bashrc.d/setjava.sh

- name: Switch on default version
  shell: "~/.bashrc.d/setjava.sh {{ default_version }}"
